version: "3"

services:
# ----------------------------------------------------------------------------------------------------------------------

  db:
    image: mysql:8.0.33

    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - db_config:/etc/mysql/conf.d
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - 3306:3306

    healthcheck:
        test: ["CMD", "curl", "-f", "http://db:3306"]
        interval: 10s
        timeout: 10s
        retries: 5

    networks:
      - vir1-network

# ----------------------------------------------------------------------------------------------------------------------
  back:
    image: cadavrexski_back
    container_name: back

    depends_on:
      db:
        condition: service_healthy
    
    ports:
      - 1234:1234

    environment:
      - SERVER_PORT=1234
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

    networks:
      - vir1-network

# ----------------------------------------------------------------------------------------------------------------------
  front:
    image: cadavrexski_front
    container_name: front

    ports: 
      - 5173:5173

    networks:
      - vir1-network

    environment:
      - VITE_APP_BACKEND_HOST=${VITE_APP_BACKEND_HOST}
      - VITE_APP_BACKEND_PORT=${VITE_APP_BACKEND_PORT}

# ----------------------------------------------------------------------------------------------------------------------
  proxy:
    image: nginx:stable-alpine3.17-slim
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back
      - front 


volumes:
  db_data:
  db_config:

networks:
  vir1-network:
    name: vir1-network
    driver: bridge
